package diploma.university.entity.enums;

public enum UserState {
    BASIC_STATE,
    WAIT_FOR_USERNAME_STATE,
    WAIT_FOR_PASSWORD_STATE,
    WAIT_FOR_PASSWORD_CONFIRM_STATE,
    WAIT_FOR_ROLE_STATE,
    WAIT_FOR_PHONE_STATE,
    WAIT_FOR_EMAIL_STATE,
    WAIT_FOR_LOGIN_PASSWORD_STATE,
    CREATE_CARD_TITLE,        // Введення назви картки
    CREATE_CARD_DESCRIPTION,  // Введення опису
    CREATE_CARD_CONTACT,      // Контактна інформація
    CREATE_CARD_IMPORTANCE,
    IN_VOLUNTEER_CARDS_MENU,
    VIEW_CARDS_LIST,
    VIEW_CARD_DETAILS,
    VIEW_TAKEN_CARDS_LIST,
    VIEW_TAKEN_CARD_DETAILS, VIEW_OWN_CARDS_LIST, VIEW_OWN_CARD_DETAILS, EDIT_CARD_TITLE, EDIT_CARD_MENU, EDIT_CARD_CONTACT, EDIT_CARD_IMPORTANCE, EDIT_CARD_DESCRIPTION, IN_MAIN_MENU
}
