package diploma.university.entity.enums;

public enum UserState {
    BASIC_STATE,
    WAIT_FOR_USERNAME_STATE,
    WAIT_FOR_PASSWORD_STATE,
    WAIT_FOR_PASSWORD_CONFIRM_STATE,
    WAIT_FOR_ROLE_STATE,
    WAIT_FOR_PHONE_STATE,
    WAIT_FOR_EMAIL_STATE,
    WAIT_FOR_LOGIN_PASSWORD_STATE,
    IN_MAIN_MENU,
    IN_PROFILE_MENU
}
